CREATE SCHEMA LogicSample
;

SET SCHEMA LogicSample
;


CREATE TABLE "customers" (
  "name" varchar(45) PRIMARY KEY,
  "balance" decimal(19,4),
  "credit_limit" decimal(19,4) NOT NULL,
  "notes" varchar(50),
  "customer_level" varchar(1),
  "is_credit_pre_approved" boolean,
  "big_order_count" int,
  "max_unpaid_order" decimal(19,4),
  "ts" timestamp
)
;

CREATE TABLE "departments" (
  "name" varchar(45) PRIMARY KEY,
  "managed_by" varchar(45),
  "head_department_name" varchar(45),
  "sum_sub_department_budget" decimal(19,4),
  "budget" decimal(19,4),
  "budget_with_sub_department_budget" decimal(19,4),
  "notes" varchar(500),
  "secret_agenda" varchar(50),
  "ts" timestamp,
  CONSTRAINT "headDepartment" FOREIGN KEY ("head_department_name") REFERENCES "departments" ("name") ON DELETE CASCADE ON UPDATE RESTRICT
)
;

CREATE INDEX "Manager" ON "departments" ("managed_by")
;

CREATE TABLE "employees" (
  "name" varchar(45) PRIMARY KEY,
  "base_salary" decimal(10,4),
  "employee_type" char(12) NOT NULL,
  "ts" timestamp,
  "visible_to" char(30),
  "department_name" varchar(45),
  "on_loan_department_name" varchar(45),
  "notes" varchar(200),
  CONSTRAINT "reportsTo__reportingEmployees" FOREIGN KEY ("department_name") REFERENCES "departments" ("name") ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT "onLoanTo__onLoanEmployees" FOREIGN KEY ("on_loan_department_name") REFERENCES "departments" ("name") ON DELETE RESTRICT ON UPDATE RESTRICT
)
;

CREATE TABLE "empsales" (
  "ts" timestamp,
  "employee_name" varchar(45),
  "year" int,
  "month" int,
  "total_sales" decimal(19,4),
  PRIMARY KEY ("employee_name", "year", "month"),
  CONSTRAINT "empSalesEmployee" FOREIGN KEY ("employee_name") REFERENCES "employees" ("name") ON DELETE NO ACTION ON UPDATE NO ACTION
)
;

CREATE TABLE "employee_audits" (
  "ident" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "base_salary" decimal(19,4),
  "base_salary_old" decimal(19,4),
  "employee_name" varchar(45),
  CONSTRAINT "auditedEmployee" FOREIGN KEY ("employee_name") REFERENCES "employees" ("name") ON DELETE CASCADE ON UPDATE RESTRICT
)
;

CREATE TABLE "employee_raise_service" (
  "ident" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "percent_raise_to_give" DECIMAL(5,2) NOT NULL ,
  "current_salary" DECIMAL(19,4) DEFAULT NULL ,
  "new_salary" DECIMAL(19,4),
  "employee_name" varchar(45),
  CONSTRAINT "employeeForRaise" FOREIGN KEY ("employee_name") REFERENCES "employees" ("name") ON DELETE NO ACTION ON UPDATE NO ACTION
)
;

CREATE TABLE "lineitems" (
  "ident" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "product_name" varchar(45) NOT NULL,
  "quantity_ordered" int,
  "part_price" decimal(19,4),
  "amount" decimal(19,4),
  "kit_quantity_ordered" int,
  "kit_number_required" int,
  "kit_component_count" int,
  "kit_item_ident" BIGINT,
  "notes" varchar(50),
  "is_ready" boolean DEFAULT false,
  "order_ident" BIGINT NOT NULL
)
;

CREATE INDEX "KitItem" ON "lineitems" ("kit_item_ident")
;
CREATE INDEX "Part" ON "lineitems" ("product_name")
;


CREATE TABLE "lineitem_notes" (
  "ident" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "special_handling" VARCHAR(50),
  "item_ident" bigint NOT NULL,
  CONSTRAINT "itemForNote" FOREIGN KEY ("item_ident") REFERENCES "lineitems" ("ident") ON DELETE NO ACTION ON UPDATE NO ACTION
)
;


CREATE TABLE "orders" (
  "ident" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "amount_total" decimal(19,4),
  "amount_discounted" decimal(19,4),
  "amount_paid" decimal(19,4),
  "amount_un_paid" decimal(19,4),
  "is_ready" boolean,
  "approving_officer" varchar(10),
  "officer_item_usage_approval" varchar(50),
  "unresolved_usage_count" int,
  "placed_date" date,
  "due_date" date,
  "salesrep_name" varchar(45),
  "customer_name" varchar(45),
  "cloned_from_order_ident" bigint,
  "item_count" int,
  "empsales_year" int,
  "empsales_month" int,
  CONSTRAINT "customer" FOREIGN KEY ("customer_name") REFERENCES "customers" ("name") ON UPDATE RESTRICT,
  CONSTRAINT "salesRep" FOREIGN KEY ("salesrep_name") REFERENCES "employees" ("name") ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT "empSales" FOREIGN KEY ("salesrep_name", "empsales_year", "empsales_month") REFERENCES "empsales" ("employee_name", "year", "month") ON DELETE NO ACTION ON UPDATE NO ACTION
)
;


CREATE TABLE "lineitem_usages" (
  "ident" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "explanation" varchar(500),
  "order_ident" bigint,
  "item_ident" bigint NOT NULL,
  CONSTRAINT "orderForUsage" FOREIGN KEY ("order_ident") REFERENCES "orders" ("ident") ON DELETE NO ACTION  ON UPDATE NO ACTION,
  CONSTRAINT "itemForUsage" FOREIGN KEY ("item_ident") REFERENCES "lineitems" ("ident") ON DELETE NO ACTION ON UPDATE NO ACTION
)
;

CREATE TABLE "order_issues" (
  "ident" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "Issue" varchar(500),
  "DateStamp" timestamp,
  "po_ident" bigint
)
;

CREATE TABLE "payments" (
  "ident" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "amount" decimal(19,4),
  "amount_un_disbursed" decimal(19,4),
  "placed_date" date,
  "customer_name" varchar(45),
  CONSTRAINT "paymentCustomer" FOREIGN KEY ("customer_name") REFERENCES "customers" ("name") ON DELETE CASCADE ON UPDATE RESTRICT
)
;

CREATE TABLE "payment_order_allocations" (
  "ident" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "order_ident" bigint NOT NULL,
  "payment_ident" bigint NOT NULL,
  "amount" decimal(19,4),
  CONSTRAINT "payment" FOREIGN KEY ("payment_ident") REFERENCES "payments" ("ident") ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT "allocationOrder" FOREIGN KEY ("order_ident") REFERENCES "orders" ("ident") ON DELETE CASCADE ON UPDATE RESTRICT
)
;

CREATE TABLE "products" (
  "name" varchar(45) PRIMARY KEY,
  "price" decimal(19,4),
  "quantity_on_hand" int,
  "total_quantity_ordered" int,
  "quantity_reorder" int,
  "is_reorder_required" boolean,
  "count_components" int,
  "sum_components_value" decimal(19,4),
  "needs_usage_terms" boolean NOT NULL,
  "is_active" boolean,
  "notes" varchar(500),
  "is_secret" boolean,
  "ts" timestamp
)
;

CREATE TABLE "product_billofmaterials" (
  "ident" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "product_name_kit" varchar(45) NOT NULL,
  "product_name" varchar(45) NOT NULL,
  "kit_number_required" int,
  "value" decimal(19,4),
  CONSTRAINT "kit__components" FOREIGN KEY ("product_name_kit") REFERENCES "products" ("name") ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT "product__inKits" FOREIGN KEY ("product_name") REFERENCES "products" ("name") ON DELETE CASCADE ON UPDATE RESTRICT
)
;

CREATE TABLE "valid_customerlevel" (
  "ident" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000, INCREMENT BY 1),
  "ts" timestamp,
  "level_stored" varchar(1) NOT NULL,
  "description" varchar(500)
)
;

ALTER TABLE "departments"
  ADD CONSTRAINT "manager" FOREIGN KEY ("managed_by") 
  REFERENCES "employees" ("name") 
  ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE "lineitems"
  ADD CONSTRAINT "kitItem" FOREIGN KEY ("kit_item_ident")
  REFERENCES "lineitems" ("ident")
  ON DELETE CASCADE ON UPDATE RESTRICT
;

ALTER TABLE "lineitems"
  ADD CONSTRAINT "product" FOREIGN KEY ("product_name")
  REFERENCES "products" ("name")
  ON DELETE CASCADE ON UPDATE RESTRICT
;

ALTER TABLE "lineitems"
  ADD CONSTRAINT "itemOrder" FOREIGN KEY ("order_ident")
  REFERENCES "orders" ("ident")
  ON DELETE CASCADE ON UPDATE RESTRICT
;
